### ISSUE TITLE
Move to `rust-seq`?

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [imartayan/minimizer-queue#2]
cc @rob-p

Since this is a main dependency of `minimizer-iter`, and also since I would like to make this faster, could we also move this into `rust-seq`?

**Comment by RagnarGrootKoerkamp** [comment]
Actually, they could be in the same repo in a workspace, since they're so coupled, possible also with nthash even (but not sure about that)

**Comment by imartayan** [comment]
Sure, we can move it to rust-seq.
I would rather keep the two crates separated though, the data structure can be useful on its own for some use cases.

**Comment by rob-p** [comment]
I am indifferent to whether it's one or two crates, but agree that if the queue is of independent utility, it's nice to have two separate crates / repos.  Anyway, we'd be happy to have it in rust-seq!

**Comment by RagnarGrootKoerkamp** [comment]
Yeah they should be separate crates. But since they're used together having them in a workspace makes it a bit easier to make changes to both of them at the same time probably.

But separate repos also works; that's a bit simpler for discoverability usually.

**Comment by imartayan** [comment]
Alright, I transfered it to rust-seq!
